[module]
  [module.hugoVersion]
    extended = true

  [[module.imports]]
    disable = false
    ignoreConfig = false
    path = "github.com/craftyphotons/wilson"

  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "layouts"
    target = "layouts"

  [[module.mounts]]
    source = "data"
    target = "data"

  [[module.mounts]]
    source = "assets"
    target = "assets"
    